name: teaching-microeconometrics

channels:
- defaults
- conda-forge
- opensourceeconomics
- r

dependencies:
- numpy
- libgfortran
- pandas
- sphinx>=1.4
- numba==0.48.0
- linearmodels
- statsmodels
- respy
- flake8
- pytest
- pytest-black
- pytest-flake8
- black
- scipy
- jupyterlab
- matplotlib
- seaborn
- jupyter
- jupyter_contrib_nbextensions
- jupyter_nbextensions_configurator
- ipython
- ipykernel
- pip
- pygraphviz
- rise
- r-essentials
- r-icc
- r-haven=2.3.1
- r-msm=1.6.8
- r-plm=2.2_3
- libiconv
- xlrd
- nbsphinx
- simplegeneric
- nb_black
- nbdime
- scikit-learn
- chaospy
- estimagic
- pip:
    - rpy2
    - black-nb
    - flake8-nb
    - linearmodels
    - openpyxl
    - scikit-learn
    - sphinx_rtd_theme
    - nbsphinx
    - cairosvg
    - sphinxcontrib-bibtex
    - sphinxcontrib-svg2pdfconverter[CairoSVG]
    - grmpy
